receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  clickhouse:
    endpoint: tcp://clickhouse-server:9000?dial_timeout=10s&compress=lz4
    database: default
    ttl_days: 3
    traces_table_name: signoz_traces
    logs_table_name: otel_logs
    metrics_table_name: signoz_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  
  logging:
    verbosity: detailed

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s
  # signozspanmetrics/cumulative:
  #   metrics_exporter: clickhouse
  #   metrics_flush_interval: 60s
  #   latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 50ms, 100ms, 250ms, 500ms, 1000ms, 1400ms, 2000ms, 5s, 10s, 20s, 40s, 60s ]
  #   dimensions_cache_size: 100000
  #   dimensions:
  #     - name: service.namespace
  #       default: default
  #     - name: deployment.environment
  #       default: default
  #     - name: 'signoz.collector.id'
  # signozspanmetrics/delta:
  #   metrics_exporter: clickhouse
  #   metrics_flush_interval: 60s
  #   latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 50ms, 100ms, 250ms, 500ms, 1000ms, 1400ms, 2000ms, 5s, 10s, 20s, 40s, 60s ]
  #   dimensions_cache_size: 100000
  #   aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
  #   dimensions:
  #     - name: service.namespace
  #       default: default
  #     - name: deployment.environment
  #       default: default
  #     - name: signoz.collector.id

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse,  logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]